add template for personal.vim; improve register_dotvim to use template of personal.vim in case personal.vim doesn't exist

diff --git a/register_dotvim b/register_dotvim
--- a/register_dotvim
+++ b/register_dotvim
@@ -3,17 +3,27 @@ cd $(dirname "$0")
 
 register_file() {
 	file="$1"
-	[ -z "$file" ] && echo "No file name supplied" && return
-	[ -h "$HOME/$file" ] && rm "$HOME/$file"
+	[ -z "$file" ] && echo "Error: No file name provided." 1>&2 && return
+	[ -h "$HOME/$file" -o ! -e "$HOME/$file" ] && rm -f "$HOME/$file"
 	if [ "$file" = ".vim" ]; then
-		[ ! -e "$HOME/$file" ] && ln -s "$PWD" "$HOME/$file"
+		if [ ! -e "$HOME/$file" ]; then
+			ln -s "$PWD" "$HOME/$file"
+		fi
 	elif [ "$file" = ".vimrc" ]; then
-		[ ! -e "$HOME/$file" ] && ln -s "$PWD/vimrc" "$HOME/$file"
+		if [ ! -e "$HOME/$file" ]; then
+			ln -s "$PWD/vimrc" "$HOME/$file"
+		fi
 	else
-		[ ! -e "$HOME/$file" ] && ln -s "$PWD/$file" "$HOME/$file"
+		if [ ! -e "$HOME/$file" ]; then
+			ln -s "$PWD/$file" "$HOME/$file"
+		fi
 	fi
 }
 
 for i in .vim .vimrc; do
 	register_file $i
 done
+
+if [ ! -e personal.vim ] && [ -e .personal.vim ]; then
+	cp -L .personal.vim personal.vim
+fi
